// GENERATED by scripts/annotations.mjs from public/annotations/*.svg. Do not edit by hand.
// A mark whose source is "placeholder" has no hand-drawn file yet.
export const ANNOTATIONS = {
  "underline": {
    "viewBox": "0 0 120 12",
    "d": "M2.5 8.2C14 6.9 25.5 8.9 38 8.1S62 5.6 76 6.6 101 9.1 117.5 6.2",
    "source": "placeholder"
  },
  "circle": {
    "viewBox": "0 0 200 120",
    "d": "M160 14C124 2 52 6 22 30 2 46 8 86 46 102c40 16 112 14 142-8 18-14 14-44-12-62C148 12 104 6 74 12",
    "source": "placeholder"
  },
  "stamp": {
    "viewBox": "0 0 200 56",
    "d": "M9.5 4.2C48 2.9 104 3.6 190.8 4.4c3.2.1 5 2 5.1 5.3.3 12.4.2 25.1-.2 37.4-.1 3.2-2.1 5-5.3 5C141 52.6 63 53.4 9.6 52.3c-3.3-.1-5.2-2-5.3-5.2-.4-12.7-.3-25.4.2-37.9.1-3.1 1.9-4.9 5-5z",
    "source": "placeholder"
  }
} as const;
