// Reads the hand-drawn marks in public/annotations/*.svg and writes lib/annotations.ts.
// A missing file keeps its placeholder, so the site always builds. Runs before `next build`.
//   underline.svg  any aspect; drawn stretched under a link (viewBox is used as-is)
//   circle.svg     a loop around a word, roughly 5:3
//   stamp.svg      the rubber-stamp border, roughly 200:56
import { existsSync, readFileSync, writeFileSync } from "node:fs";

const PLACEHOLDERS = {
  underline: { viewBox: "0 0 120 12", d: "M2.5 8.2C14 6.9 25.5 8.9 38 8.1S62 5.6 76 6.6 101 9.1 117.5 6.2" },
  circle: { viewBox: "0 0 200 120", d: "M160 14C124 2 52 6 22 30 2 46 8 86 46 102c40 16 112 14 142-8 18-14 14-44-12-62C148 12 104 6 74 12" },
  stamp: {
    viewBox: "0 0 200 56",
    d: "M9.5 4.2C48 2.9 104 3.6 190.8 4.4c3.2.1 5 2 5.1 5.3.3 12.4.2 25.1-.2 37.4-.1 3.2-2.1 5-5.3 5C141 52.6 63 53.4 9.6 52.3c-3.3-.1-5.2-2-5.3-5.2-.4-12.7-.3-25.4.2-37.9.1-3.1 1.9-4.9 5-5z",
  },
};

const out = {};
for (const [name, fallback] of Object.entries(PLACEHOLDERS)) {
  const file = `public/annotations/${name}.svg`;
  if (!existsSync(file)) {
    out[name] = { ...fallback, source: "placeholder" };
    continue;
  }
  const svg = readFileSync(file, "utf8");
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  const ds = [...svg.matchAll(/<path[^>]*\sd="([^"]+)"/g)].map((m) => m[1].replace(/\s+/g, " ").trim());
  if (!viewBox || ds.length === 0) throw new Error(`${file}: needs a viewBox and at least one <path d="…"> (convert shapes and strokes to paths)`);
  if (/transform=/.test(svg)) console.warn(`${file}: transforms are ignored; flatten them before exporting.`);
  out[name] = { viewBox, d: ds.join(" "), source: file };
}

writeFileSync(
  "lib/annotations.ts",
  `// GENERATED by scripts/annotations.mjs from public/annotations/*.svg. Do not edit by hand.
// A mark whose source is "placeholder" has no hand-drawn file yet.
export const ANNOTATIONS = ${JSON.stringify(out, null, 2)} as const;
`,
);
console.log(Object.entries(out).map(([k, v]) => `${k}: ${v.source}`).join("\n"));
